### ISSUE TITLE
Disable Battery Warnings not found in the menu bar

### ISSUE THREAD

**Issue by davidhedlund** [pR0Ps/DisableBatteryWarnings#4]
I cannot find Disable Battery Warnings in the App list. Can you please add it?

**Comment by pR0Ps** [comment]
App list?

**Comment by davidhedlund** [comment]
See this link for "Apps": http://www.dummies.com/consumer-electronics/tablets/samsung-galaxy-tab/overview-of-the-apps-menu-on-the-samsung-galaxy-tab-home-screen/

**Comment by pR0Ps** [comment]
It's not in there because it's not really an app. There are no activities or anything for an icon to launch when you tap it. It's an Xposed module that can be installed/enabled/disabled/uninstalled from within the Xposed Installer.

**Comment by davidhedlund** [comment]
I would still be nice to be able to turn on/off the service and to uninstall it from the Apps menu like people normally do.

**Comment by pR0Ps** [comment]
Sorry, I'm not going to give it a useless activity make make it clutter up the app drawer. It can be uninstalled from within the Xposed installer or from the list of apps in Android settings -> Apps -> Downloaded.

**Comment by davidhedlund** [comment]
Ok.
