### ISSUE TITLE
Version 1.1 broken

### ISSUE THREAD

**Issue by davidhedlund** [pR0Ps/DisableBatteryWarnings#5]
I have installed version 1.1 of the app but it doesn't work. The service is running.

**Comment by pR0Ps** [comment]
What version of Android are you running?

**Comment by davidhedlund** [comment]
> What version of Android are you running?

4.4.4

**Comment by pR0Ps** [comment]
Sorry, I should've been more clear:
 - Are you using AOSP? LineageOS? Cyanogenmod? Some other OS?
 - What version of Xposed are you running? (in the Xposed Installer app in the "Framework" section, the "XposedBridge.jar" version)

**Comment by davidhedlund** [comment]
> * Are you using AOSP? LineageOS? Cyanogenmod? Some other OS?

No, just Android.

> * What version of Xposed are you running? (in the Xposed Installer app in the "Framework" section, the "XposedBridge.jar" version)

I don't even know what Xposed is. I just installed the [F-Droid build](https://f-droid.org/en/packages/ca.cmetcalfe.xposed.disablebatterywarnings/) of Disable Battery Warnings.

**Comment by davidhedlund** [comment]
Thanks. Can you please tell me if it's possible to install Xposed on F-Droid?

https://f-droid.org/wiki/page/de.robv.android.xposed.installer -> [View in repository](https://f-droid.org/repository/browse/?fdid=de.robv.android.xposed.installer) says
> 404 Page Not Found

**Comment by davidhedlund** [comment]
Can you add a function to reject installation if Xpose is not installed?

**Comment by pR0Ps** [comment]
As far as I know, the installer is not available on F-Droid. You'll have to get it from the [Xposed Module Repo](http://repo.xposed.info/module/de.robv.android.xposed.installer) or [build it yourself](https://github.com/rovo89?tab=repositories&q=xposed).

Since it's just an apk, there's no way for me to make it fail to install if the Xposed framework is not available - it just won't do anything.

**Comment by davidhedlund** [comment]
> Since it's just an apk, there's no way for me to make it fail to install if the Xposed framework is not available - it just won't do anything.

True, but you can display a message when the service run to tell if Xpose is not installed.

**Comment by davidhedlund** [comment]
Hmm... Am I right?

**Comment by pR0Ps** [comment]
There is no service that runs, there is only an Xposed entry point. Furthermore, even if there was a service, it would not be started until the user manually invoked the app. At this point we're back to #4 and might as well have a main activity that says: "If you don't have Xposed, this isn't going to work".

My goal for this project is to provide a module that just implements the core functionality (ie. it doesn't need any user-facing activities to work, so it doesn't have them). If a more conventional experience with an icon in the app drawer and error messages for unsupported environments is something you feel people would like, I would recommend forking the project and releasing a more user-friendly flavor of it.

**Comment by davidhedlund** [comment]
Ok, thank you very much for taking your time to explain this to me.
